/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import javazoom.jl.player.Player;
import javazoom.jl.decoder.*;
import java.awt.Image;


public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    Timer timer; 
    int hours, minutes, seconds; 
    private File selectedFile; 
    private FileInputStream ringtoneFile;
    private Player player; 
    private Thread playerThread; 
    
    private ImageIcon clockImage = new ImageIcon("C:/Users/dell/Downloads/clock.jpg");
    Image clockRes = clockImage.getImage().getScaledInstance(64,64,Image.SCALE_SMOOTH);
    ImageIcon clock = new ImageIcon(clockRes);
    
    private ImageIcon musicImage = new ImageIcon("C:/Users/dell/Downloads/download.png");
    Image musicRes = musicImage.getImage().getScaledInstance(64,64,Image.SCALE_SMOOTH);
    ImageIcon music = new ImageIcon(musicRes); 
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Count Down Clock");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText(":");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Hours");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Minutes");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Seconds");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(78, 33));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(78, 33));
        jComboBox2.setVerifyInputWhenFocusTarget(false);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Select File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Listen Ringtone");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addGap(119, 119, 119)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(121, 121, 121)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Count down function
    public void startCountdown() {
        timer = new Timer(1000, new ActionListener() { // Setting an delay of 1000ms or 1 sec for updation
            @Override
            public void actionPerformed(ActionEvent e) {
                if (seconds == 0 && minutes == 0 && hours == 0) { // checking if the timer is finished
                    timer.stop();
                    jLabel6.setText("Time's up!"); 
                    jComboBox1.setEnabled(true);
                    jComboBox2.setEnabled(true);
                    jComboBox3.setEnabled(true);
                    jButton1.setText("Start"); 
                    playRingtone(); 
                    jButton4.setText("Listen Ringtone");

                    String[] options = {"Stop"};  // Setting option pane for stoping the clock
                    javax.swing.JOptionPane.showOptionDialog( 
                            SwingUtilities.getWindowAncestor(jButton1),
                            "Timer Finished!",
                            "Timer Finished",
                            javax.swing.JOptionPane.DEFAULT_OPTION,
                            javax.swing.JOptionPane.INFORMATION_MESSAGE,
                            null,
                            options,
                            options[0]
                    );
                    stopRingtone();
                    jLabel6.setText("");
                    return;
                }

                // Time decrement logic
                if (seconds == 0) { 
                    if (minutes == 0) {
                        if (hours != 0) { 
                            hours--;
                            minutes = 59; // after an hour is passed we are decrementing it and setting minutes
                        }
                    } else { 
                        minutes--;
                        seconds = 59; 
                    }
                } else {
                    seconds--; // decrementing seconds
                }

                jComboBox1.setSelectedIndex(hours); 
                jComboBox2.setSelectedIndex(minutes);
                jComboBox3.setSelectedIndex(seconds);
            }
        });
        timer.start();
    }
    
    // ringtone function
    private void playRingtone() {
        if (selectedFile != null && selectedFile.exists() && selectedFile.isFile()) { // Checking for file
            try {
                ringtoneFile = new FileInputStream(selectedFile);
                player = new Player(ringtoneFile);
                playerThread = new Thread(() -> { // Creating thread for player
                    try {
                        player.play();
                        player = null;
                        playerThread = null;
                    } catch (JavaLayerException e) {
                        e.printStackTrace();
                        SwingUtilities.invokeLater(() -> jLabel6.setText("Error playing MP3: " + e.getMessage()));
                    }
                });
                playerThread.start(); // Starting player
                jButton4.setText("Stop Ringtone");
            } catch (FileNotFoundException | JavaLayerException e) {
                e.printStackTrace();
                SwingUtilities.invokeLater(() -> jLabel6.setText("Error initializing MP3 player: " + e.getMessage()));
            }
        } else {
            JOptionPane.showMessageDialog(
               this, 
               "No valid ringtone file selected.",
               "Timer Status", 
               JOptionPane.ERROR_MESSAGE
            );
            jButton4.setText("Listen Ringtone");
        }
    }

    // Function for stopping ringtone
    private void stopRingtone() {
        if (player != null && playerThread != null) { 
            player.close();
            playerThread.interrupt();
            player = null;
            playerThread = null;
        }
    }
    
    // Function for Start button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (selectedFile == null) { // Checking for file
            javax.swing.JOptionPane.showMessageDialog(
                null,
                "Please select a song file before starting the timer.", 
                "No Song File Selected", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if ((jButton1.getText()).equals("Start")) { // Starting count down
            hours = Integer.parseInt((String) jComboBox1.getSelectedItem()); // Taking inputs
            minutes = Integer.parseInt((String) jComboBox2.getSelectedItem());
            seconds = Integer.parseInt((String) jComboBox3.getSelectedItem());

            jComboBox1.setEnabled(false); // Disabling input boxes
            jComboBox2.setEnabled(false);
            jComboBox3.setEnabled(false);

            jButton1.setText("Pause");
            startCountdown();  // Starting countdown
            JOptionPane.showMessageDialog( 
                    this, 
                    "Countdown Started", 
                    "Timer Status", 
                    JOptionPane.INFORMATION_MESSAGE,
                    clock
            );
        } else if ((jButton1.getText()).equals("Pause")) { // To pause the countdown
            timer.stop(); // Stopping countdown
            jComboBox1.setEnabled(true);
            jComboBox2.setEnabled(true);
            jComboBox3.setEnabled(true);
            jButton1.setText("Resume");
            JOptionPane.showMessageDialog( 
                this,
                "Countdown Paused", 
                "Timer Status", 
                JOptionPane.INFORMATION_MESSAGE,
                clock
            );
        } else if ((jButton1.getText()).equals("Resume")) { // Restarting Countdown
                hours = Integer.parseInt((String) jComboBox1.getSelectedItem());
                minutes = Integer.parseInt((String) jComboBox2.getSelectedItem());
                seconds = Integer.parseInt((String) jComboBox3.getSelectedItem());
                jComboBox1.setEnabled(false);
                jComboBox2.setEnabled(false);
                jComboBox3.setEnabled(false);
                jButton1.setText("Pause");
                startCountdown();
                JOptionPane.showMessageDialog( 
                    this, 
                    "Countdown Resumed", 
                    "Timer Status", 
                    JOptionPane.INFORMATION_MESSAGE,
                    clock
                );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Function for Reset button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        timer.stop(); // Stopping countdown and Setting time variables to 0
        hours = 0;
        minutes = 0;
        seconds = 0;

        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        jComboBox3.setEnabled(true);
        
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);

        jLabel6.setText("");
        jButton1.setText("Start");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    // Function of select file button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(); // To take file input
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3"); // filter for mp3 files only
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) { // Checking for selected file
            selectedFile = fileChooser.getSelectedFile();
            if (selectedFile.exists() && selectedFile.isFile()) { // checking if file exists 
                try {
                    ringtoneFile = new FileInputStream(selectedFile);
                    JOptionPane.showMessageDialog(
                    this, 
                    "Ringtone selected: " + selectedFile.getName(), 
                    "Timer Status", 
                    JOptionPane.INFORMATION_MESSAGE,
                    music
                    );
                } catch (FileNotFoundException e) { // Error if file is not selected as expected
                    JOptionPane.showMessageDialog(
                        this, 
                        "Error selecting file.", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE
                    );

                    e.printStackTrace();
                }
            } else { // if file does not exists
                JOptionPane.showMessageDialog( 
                    this,
                    "Selected file does not exist or is invalid.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //function for button listen ringtone
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if ((jButton4.getText()).equals("Listen Ringtone")) {
            playRingtone();
        } else if ((jButton4.getText()).equals("Stop Ringtone")) {
            stopRingtone();
            jButton4.setText("Listen Ringtone");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
